version: '3'

services:
  db:
    image: mysql:8.0.11
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=airport
    - MYSQL_USER=airport
    - MYSQL_PASSWORD=airport
    - MYSQL_ROOT_PASSWORD=airport
    - MYSQL_HOST=localhost
